default:
  image: ubuntu:20.04
  before_script:
    - apt -y update
    - apt -y upgrade
    - apt -y install apt-utils

test_app:
  stage: test
  before_script:
    - apt -y update
    - apt -y upgrade
    - apt -y install apt-utils
    - apt -y install curl 
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt -y install nodejs
    - node -v
    - npm install -g npm
    - npm install jest -- save-dev jest
    #ad
  script: 
    - npm run test
  allow_failure: true

deploy_app:
  stage: deploy
  before_script:
    - apt -y update
    - apt -y upgrade
    - apt -y install openssh-client
    - touch id.rsa
    - echo "$SSH_PRIVATE_KEY" > id.rsa
    - chmod 400 id.rsa
  script:
    - ssh -i id.rsa -o StrictHostKeyChecking=no ubuntu@ec2-54-89-51-16.compute-1.amazonaws.com "cd get-lab; git pull origin main"

